AWSTemplateFormatVersion: 2010-09-09
Description: VPC

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: true

Outputs:

  VpcId:
    Value: !Ref VPC
